import {StyleSheet,Dimensions} from 'react-native'
import { ifIphoneX } from 'react-native-iphone-x-helper';
const WindowWidth = Dimensions.get('window').width
export default StyleSheet.create({
    container:{
        flex:1,
        backgroundColor:'rgba(0,0,0,0.02)'
    },
    header:{
        height:80,
        backgroundColor:'#fff',
        flexDirection:'row',
        alignItems:'center',   
        shadowOpacity:0.4,
        shadowOffset:{width:2,height:0},
        justifyContent: 'center',
        width: WindowWidth
    },
    back:{
        height:24,
        width:24,
        
        //borderWidth:1
    },
    searchItem:{
        fontFamily:'Lato-Regular',
        fontSize:16,
        fontWeight:'bold',
        color:'#000',
       
    },
    searchSection:{
        marginVertical:30,
        // alignItems:'center',
        // justifyContent:'center',
        
        //paddingHorizontal: 10
    },
    body:{
        height:60,
        width:WindowWidth-48,
        backgroundColor:'#F0F0F0',
        borderRadius:100,
        flexDirection:'row',
        alignItems:'center',
    },
    textInput:{
        flex:1,
        fontSize:18,
        color:'#000',
        fontFamily:'Lato-Regular',
        marginLeft:16
    },
    iconSearch:{
        marginLeft:10,
        height:16,
        width:16,
        marginRight:24,
    },
    line:{
        height:1,
        backgroundColor:'#F0F0F0',
       // marginHorizontal:24,
    },
    recentSearch:{
        paddingLeft:30,
        backgroundColor:'#fff',
        paddingVertical:25,
    },
    head:{
        color:'#000',
        fontFamily:'Lato-Regular',
        fontWeight:'bold',
        fontSize:18,
        marginBottom:16,
    },
    item:{
        color:'#000',
        fontFamily:'Lato-Regular',
        fontSize:16,
    },
    recentViewed:{
        paddingTop:25,
    },
    
    productImages:{
        backgroundColor:'#F0F0F0',
    },
    img:{
        marginRight:10,
        width:100,
        height:100,
        marginVertical:10,
    },
    cancel:{
        color:'#4A90E2',
        fontSize:16,
        fontFamily:'Lato-Regular',
        marginLeft:15
    },



    FlatListcontainer:{
        paddingTop:10,
        paddingLeft:10,
        paddingRight:10,   
    },
    card:{
        flexDirection:'row',
        padding:7,
        backgroundColor:'#fff',
        borderRadius:2,  
    },
    productIcon:{
        height:100,
        width:100,
        marginRight:19,
        //borderWidth:1,
    },
    detail:{
        flexWrap: 'wrap',
        flex:1,
    },
    title:{
        marginRight:10,
        fontSize:12,
        color:'#000',
        fontFamily:'Lato-Regular',
    },
    label:{
        width:70,
        height:24,
        backgroundColor:'#FF4273', 
        marginTop:7,   
        alignItems:'center',
        justifyContent:'center',
        borderRadius:2,
    },
    labelText:{
        fontSize:13,
        color:'#fff',
        fontFamily:'Patua One',
    },
    extraInfo:{
        marginTop:5,
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between',
        //borderWidth:1,
    },
    shippingText:{
        fontSize:10,
        color:'#9B9B9B',
        fontFamily:'Lato-Regular',
        fontWeight:'bold'
    },
    extraInfoLabel:{
        //borderWidth:1,
        borderRadius:20,
        height:24,
        width:81,
        backgroundColor:'#F0F0F0',
        alignItems:'center',
        //justifyContent:'center',
        flexDirection:'row',   
    },
    extraInfoIcon:{
        height:16,
        width:12,
        marginLeft:5
    },
    superHotText:{
        //paddingLeft:4,
        fontSize:10,
        color:'#000',
        fontFamily:'Patua One',
        marginLeft:7
     },
    container1:{
        paddingTop:10,
        paddingLeft:10,
        paddingRight:10,   
    },
    card:{
        flexDirection:'row',
        padding:7,
        backgroundColor:'#fff',
        borderRadius:2,
        
    },
    productIcon:{
        height:100,
        width:100,
        marginRight:19,
        //borderWidth:1,
    },
    detail:{
        flexWrap: 'wrap',
        flex:1,
    },
    title:{
        marginRight:10,
        fontSize:12,
        color:'#000',
        fontFamily:'Lato-Regular',
       
    },
    label:{
        width:70,
        height:24,
        backgroundColor:'#FF4273', 
        //marginTop:7,   
        alignItems:'center',
        justifyContent:'center',
        position:'absolute',
        bottom:20,
        borderRadius:2,
    },
    labelText:{
        fontSize:13,
        color:'#fff',
        fontFamily:"PatuaOne-Regular",
    },
    extraInfo:{
        //marginTop:5,
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between',
        position:'absolute',
        right:10,
        bottom:0,
        width:deviceWidth-156,

        //borderWidth:1,
    },
    shippingText:{
        fontSize:10,
        color:'#9B9B9B',
        fontFamily:'Lato-Regular',
        fontWeight:'bold',
        backgroundColor:'transparent'
    },
    extraInfoLabel:{
        //borderWidth:1,
        borderRadius:20,
        height:24,
        width:81,
        backgroundColor:'#F0F0F0',
        alignItems:'center',
        //justifyContent:'center',
        flexDirection:'row',  
        marginBottom:5 
    },
    extraInfoIcon:{
        height:16,
        width:12,
        marginLeft:5,
       
    },
    superHotText:{
        //paddingLeft:4,
        fontSize:10,
        color:'#000',
        fontFamily:"PatuaOne-Regular",
        marginLeft:7,
       
     },
})