import {StyleSheet,Platform} from 'react-native'
import { ifIphoneX } from 'react-native-iphone-x-helper';
export default StyleSheet.create({
    back:{
      position:'absolute',
      ...ifIphoneX({
          top:30
      },{
        top:20,
      }),
        
        left:15,
        height:50,
        width:50,
        zIndex:1,
        opacity:1,
    },
    image:{
       // width:375,
        flex:1,
        height:250,
        zIndex:0
    },
    total:{
        marginTop:50,
        fontFamily:'Lato-Regular',
        fontSize:18,
        color:'#000',
        textAlign:'center',
    },
    totalNo:{
        marginTop:15,
        color:'#FF4273',
        fontFamily:'Lato-Regular',
        //fontSize:20,
        fontSize:80,
       // fontSize:Platform.OS === 'ios'?80:40, 
        textAlign:'center',
        fontWeight:'900',
    },
    emojys:{
        marginTop:20,
        flexDirection:'row',
        alignSelf:'center',
    },
    emoj:{
        width:60,
        height:27,
        marginLeft:5,
    },
    footer:{
        paddingBottom:110,
        marginTop:37,
        alignSelf:'center',
    },
    send:{
        textAlign:'center',
        color:'#9B9B9B',
        fontSize:14,
        fontFamily:'Lato-Regular',  
    },
    button:{
       //flex:1,
        position:'absolute',
        bottom:0,
        zIndex:0,
        right:0,
        left:0,
    },
    line:{
        height:10,
        backgroundColor:'#fff',
        shadowOpacity:3,
        shadowOffset:{width:0,height:1}
    },
    btnBackground:{
        backgroundColor:'#FF4273',
        height:70,
        alignItems:'center',
        justifyContent:'center',
        position:'absolute',
        bottom:0,
        right:0,
        left:0
    },
    buy:{
        fontFamily:'Lato-Regular',
        color:'#fff',
        fontWeight:'bold'
    },
})