# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Clickers' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for Clickers
  #  
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Messaging'
  pod 'Firebase/DynamicLinks'
  target 'Clickers-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    

  end

  target 'ClickersTests' do
    inherit! :search_paths
    # Pods for testing
  end

end


