# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Clickers' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Clickers
  #  
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Messaging'
  pod 'Firebase/DynamicLinks'
  pod 'Firebase/Invites'
  # pod 'react-native-youtube', :path => '../node_modules/react-native-youtube'
  target 'Clickers-tvOSTests' do
    inherit! :search_paths
       # Pods for testing
  end

  target 'ClickersTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
# post_install do |installer|
#   installer.pods_project.targets.each do |target|
#     if target.name == "React"
#       target.remove_from_project
#     end
#   end
# end


